/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hangman;

/**
 *
 * @author ALLEN
 */
public class Second_page extends javax.swing.JFrame {

    /**
     * Creates new form Second_page
     */
    public Second_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dead = new javax.swing.JLabel();
        Man = new javax.swing.JLabel();
        ques1 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        Dead.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\JAVA\\Project(Me, Anjon, Arefin)\\Hangman file\\logo\\hangman dead.png")); // NOI18N
        getContentPane().add(Dead);
        Dead.setBounds(630, 80, 80, 200);

        Man.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\JAVA\\Project(Me, Anjon, Arefin)\\Hangman file\\logo\\hang with man.png")); // NOI18N
        getContentPane().add(Man);
        Man.setBounds(630, 80, 80, 220);

        ques1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(ques1);
        ques1.setBounds(50, 70, 190, 30);

        Background.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\JAVA\\Project(Me, Anjon, Arefin)\\Hangman file\\logo\\Dark night1.jpg")); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 786, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

      
       Dead.setVisible(false);
       
       ques1.setText("What's your name?");
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Second_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Second_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Second_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Second_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Second_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Dead;
    private javax.swing.JLabel Man;
    private javax.swing.JLabel ques1;
    // End of variables declaration//GEN-END:variables
}
